{
    "name": "Loke - Tinder Test #47",
    "tags": ["Loke", "Tinder"],
    "platform": "windows",
    "browserType": "anty",
    "mainWebsite": "google",
    "useragent": {
        "mode": "manual",
        "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    },
    "webrtc": {"mode": "altered", "ipAddress": None},
    "canvas": {"mode": "real"},
    "webgl": {"mode": "real"},
    "webglInfo": {
        "mode": "manual",
        "vendor": "NVIDIA Corporation",
        "renderer": "NVIDIA GeForce GT 750M OpenGL Engine",
        "webgl2Maximum": '{"MAX_SAMPLES": 8, "MAX_DRAW_BUFFERS": 8, "MAX_TEXTURE_SIZE": 16384, "MAX_ELEMENT_INDEX": 4294967295, "MAX_VIEWPORT_DIMS": [16384, 16384], "MAX_VERTEX_ATTRIBS": 16, "MAX_3D_TEXTURE_SIZE": 2048, "MAX_VARYING_VECTORS": 31, "MAX_ELEMENTS_INDICES": 150000, "MAX_TEXTURE_LOD_BIAS": 15, "MAX_COLOR_ATTACHMENTS": 8, "MAX_ELEMENTS_VERTICES": 1048575, "MAX_RENDERBUFFER_SIZE": 16384, "MAX_UNIFORM_BLOCK_SIZE": 65536, "MAX_VARYING_COMPONENTS": 124, "MAX_TEXTURE_IMAGE_UNITS": 16, "MAX_ARRAY_TEXTURE_LAYERS": 2048, "MAX_PROGRAM_TEXEL_OFFSET": 7, "MIN_PROGRAM_TEXEL_OFFSET": -8, "MAX_CUBE_MAP_TEXTURE_SIZE": 16384, "MAX_VERTEX_UNIFORM_BLOCKS": 14, "MAX_VERTEX_UNIFORM_VECTORS": 1024, "MAX_COMBINED_UNIFORM_BLOCKS": 70, "MAX_FRAGMENT_UNIFORM_BLOCKS": 14, "MAX_UNIFORM_BUFFER_BINDINGS": 70, "MAX_FRAGMENT_UNIFORM_VECTORS": 1024, "MAX_VERTEX_OUTPUT_COMPONENTS": 128, "MAX_FRAGMENT_INPUT_COMPONENTS": 128, "MAX_VERTEX_UNIFORM_COMPONENTS": 4096, "MAX_VERTEX_TEXTURE_IMAGE_UNITS": 16, "MAX_FRAGMENT_UNIFORM_COMPONENTS": 4096, "UNIFORM_BUFFER_OFFSET_ALIGNMENT": 256, "MAX_COMBINED_TEXTURE_IMAGE_UNITS": 80, "MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS": 233472, "MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS": 4, "MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS": 233472, "MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS": 4, "MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS": 64}',
    },
    "clientRect": {"mode": "real"},
    "notes": {"content": None, "color": "blue", "style": "text", "icon": "info"},
    "timezone": {"mode": "auto", "value": None},
    "locale": {"mode": "auto", "value": None},
    "proxy": {
        "name": "test proxy",
        "host": "145.239.27.73",
        "port": "13991",
        "type": "socks5",
        "login": "root",
        "password": "321",
    },
    "statusId": 0,
    "geolocation": {
        "mode": "auto",
        "latitude": None,
        "longitude": None,
        "accuracy": None,
    },
    "cpu": {"mode": "manual", "value": 4},
    "memory": {"mode": "manual", "value": 8},
    "screen": {"mode": "real", "resolution": None},
    "audio": {"mode": "real"},
    "mediaDevices": {
        "mode": "real",
        "audioInputs": None,
        "videoInputs": None,
        "audioOutputs": None,
    },
    "ports": {"mode": "protect", "blacklist": "3389,5900,5800,7070,6568,5938"},
    "doNotTrack": False,
    "args": [],
    "platformVersion": "10.15.7",
    "uaFullVersion": "110.0.5304.87",
    "login": "",
    "password": "",
    "appCodeName": "Mozilla",
    "platformName": "MacIntel",
    "connectionDownlink": 10,
    "connectionEffectiveType": "4g",
    "connectionRtt": 100,
    "connectionSaveData": 0,
    "cpuArchitecture": "",
    "osVersion": "10.15.7",
    "vendorSub": "",
    "productSub": "20030107",
    "vendor": "Google Inc.",
    "product": "Gecko",
}


{
    "name": "Loke - Tinder Test #47",
    "tags": ["Loke", "Tinder"],
    "platform": "Win32",
    "browserType": "chrome",
    "mainWebsite": "google",
    "useragent": {
        "mode": "manual",
        "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    },
    "webrtc": {"mode": "altered", "ipAddress": None},
    "canvas": {"mode": "real"},
    "webgl": {
        "unmaskedVendor": "Google Inc. (Intel)",
        "unmaskedRenderer": "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)",
    },
    "webglInfo": {
        "mode": "manual",
        "vendor": "NVIDIA Corporation",
        "renderer": "NVIDIA GeForce GT 750M OpenGL Engine",
        "webgl2Maximum": '{"MAX_SAMPLES": 8, "MAX_DRAW_BUFFERS": 8, "MAX_TEXTURE_SIZE": 16384, "MAX_ELEMENT_INDEX": 4294967295, "MAX_VIEWPORT_DIMS": [16384, 16384], "MAX_VERTEX_ATTRIBS": 16, "MAX_3D_TEXTURE_SIZE": 2048, "MAX_VARYING_VECTORS": 31, "MAX_ELEMENTS_INDICES": 150000, "MAX_TEXTURE_LOD_BIAS": 15, "MAX_COLOR_ATTACHMENTS": 8, "MAX_ELEMENTS_VERTICES": 1048575, "MAX_RENDERBUFFER_SIZE": 16384, "MAX_UNIFORM_BLOCK_SIZE": 65536, "MAX_VARYING_COMPONENTS": 124, "MAX_TEXTURE_IMAGE_UNITS": 16, "MAX_ARRAY_TEXTURE_LAYERS": 2048, "MAX_PROGRAM_TEXEL_OFFSET": 7, "MIN_PROGRAM_TEXEL_OFFSET": -8, "MAX_CUBE_MAP_TEXTURE_SIZE": 16384, "MAX_VERTEX_UNIFORM_BLOCKS": 14, "MAX_VERTEX_UNIFORM_VECTORS": 1024, "MAX_COMBINED_UNIFORM_BLOCKS": 70, "MAX_FRAGMENT_UNIFORM_BLOCKS": 14, "MAX_UNIFORM_BUFFER_BINDINGS": 70, "MAX_FRAGMENT_UNIFORM_VECTORS": 1024, "MAX_VERTEX_OUTPUT_COMPONENTS": 128, "MAX_FRAGMENT_INPUT_COMPONENTS": 128, "MAX_VERTEX_UNIFORM_COMPONENTS": 4096, "MAX_VERTEX_TEXTURE_IMAGE_UNITS": 16, "MAX_FRAGMENT_UNIFORM_COMPONENTS": 4096, "UNIFORM_BUFFER_OFFSET_ALIGNMENT": 256, "MAX_COMBINED_TEXTURE_IMAGE_UNITS": 80, "MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS": 233472, "MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS": 4, "MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS": 233472, "MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS": 4, "MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS": 64}',
    },
    "clientRect": {"mode": "real"},
    "notes": {"content": None, "color": "blue", "style": "text", "icon": "info"},
    "timezone": {"mode": "auto", "value": None},
    "locale": {"mode": "auto", "value": None},
    "proxy": {
        "name": "test proxy",
        "host": "145.239.27.73",
        "port": "13991",
        "type": "socks5",
        "login": "root",
        "password": "321",
    },
    "statusId": 0,
    "geolocation": {
        "mode": "auto",
        "latitude": None,
        "longitude": None,
        "accuracy": None,
    },
    "cpu": {"architecture": "amd64"},
    "memory": {"mode": "manual", "value": 8},
    "screen": {
        "availWidth": 1536,
        "availHeight": 816,
        "width": 1536,
        "height": 864,
        "colorDepth": 24,
        "pixelDepth": 24,
    },
    "audio": {"mode": "real"},
    "mediaDevices": {
        "mode": "real",
        "audioInputs": None,
        "videoInputs": None,
        "audioOutputs": None,
    },
    "ports": {"mode": "protect", "blacklist": "3389,5900,5800,7070,6568,5938"},
    "doNotTrack": False,
    "args": [],
    "platformVersion": "14.0.0",
    "uaFullVersion": "112.0.5615.50",
    "login": "",
    "password": "",
    "appCodeName": "Mozilla",
    "platformName": "MacIntel",
    "connectionDownlink": 10,
    "connectionEffectiveType": "4g",
    "connectionRtt": 100,
    "connectionSaveData": 0,
    "cpuArchitecture": "",
    "osVersion": "10.15.7",
    "vendorSub": "",
    "productSub": "20030107",
    "vendor": "Google Inc.",
    "product": "Gecko",
    "connection": {"downlink": 10, "rtt": 50, "effectiveType": "4g", "saveData": 0},
    "deviceMemory": 8,
    "hardwareConcurrency": 8,
    "donottrack": 0,
    "language": "",
    "languages": "",
    "appVersion": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
    "os": {"name": "Windows", "version": "10"},
    "browser": {"name": "Chrome", "version": "112.0.0.0", "shortVersion": 112},
    "voices": "[]",
    "fonts": '["Agency FB", "Arial Black", "Arial", "Bauhaus 93", "Bell MT", "Bodoni MT", "Bookman Old Style", "Broadway", "Calibri Light", "Calibri", "Californian FB", "Cambria Math", "Cambria", "Candara", "Castellar", "Centaur", "Century Gothic", "Colonna MT", "Comic Sans MS", "Consolas", "Constantia", "Copperplate Gothic Light", "Corbel", "Courier New", "Ebrima", "Engravers MT", "Forte", "Franklin Gothic Heavy", "Franklin Gothic Medium", "French Script MT", "Gabriola", "Georgia", "Gigi", "Goudy Old Style", "Haettenschweiler", "Harrington", "Impact", "Informal Roman", "Leelawadee", "Lucida Bright", "Lucida Console", "Lucida Fax", "Lucida Sans Unicode", "MS Gothic", "MS PGothic", "MS Reference Sans Serif", "MS UI Gothic", "MV Boli", "Magneto", "Malgun Gothic", "Marlett", "Matura MT Script Capitals", "Microsoft Himalaya", "Microsoft JhengHei", "Microsoft New Tai Lue", "Microsoft PhagsPa", "Microsoft Sans Serif", "Microsoft Tai Le", "Microsoft Uighur", "Microsoft YaHei", "Microsoft Yi Baiti", "MingLiU-ExtB", "MingLiU_HKSCS-ExtB", "Mongolian Baiti", "NSimSun", "Niagara Solid", "PMingLiU-ExtB", "Palace Script MT", "Palatino Linotype", "Papyrus", "Perpetua", "Playbill", "Rockwell", "Segoe Print", "Segoe Script", "Segoe UI Light", "Segoe UI Semibold", "Segoe UI Symbol", "Segoe UI", "Showcard Gothic", "SimSun", "SimSun-ExtB", "Snap ITC", "Sylfaen", "Symbol", "Tahoma", "Times New Roman", "Trebuchet MS", "Verdana", "Vladimir Script", "Webdings", "Wide Latin", "Wingdings"]',
    "webgl2Maximum": '{"UNIFORM_BUFFER_OFFSET_ALIGNMENT":256,"MAX_TEXTURE_SIZE":16384,"MAX_VIEWPORT_DIMS":[32767,32767],"MAX_VERTEX_ATTRIBS":16,"MAX_VERTEX_UNIFORM_VECTORS":4096,"MAX_VARYING_VECTORS":30,"MAX_COMBINED_TEXTURE_IMAGE_UNITS":32,"MAX_VERTEX_TEXTURE_IMAGE_UNITS":16,"MAX_TEXTURE_IMAGE_UNITS":16,"MAX_FRAGMENT_UNIFORM_VECTORS":1024,"MAX_CUBE_MAP_TEXTURE_SIZE":16384,"MAX_RENDERBUFFER_SIZE":16384,"MAX_3D_TEXTURE_SIZE":2048,"MAX_ELEMENTS_VERTICES":2147483647,"MAX_ELEMENTS_INDICES":2147483647,"MAX_TEXTURE_LOD_BIAS":2,"MAX_DRAW_BUFFERS":8,"MAX_FRAGMENT_UNIFORM_COMPONENTS":4096,"MAX_VERTEX_UNIFORM_COMPONENTS":16384,"MAX_ARRAY_TEXTURE_LAYERS":2048,"MIN_PROGRAM_TEXEL_OFFSET":-8,"MAX_PROGRAM_TEXEL_OFFSET":7,"MAX_VARYING_COMPONENTS":120,"MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS":4,"MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS":120,"MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS":4,"MAX_COLOR_ATTACHMENTS":8,"MAX_SAMPLES":16,"MAX_VERTEX_UNIFORM_BLOCKS":12,"MAX_FRAGMENT_UNIFORM_BLOCKS":12,"MAX_COMBINED_UNIFORM_BLOCKS":24,"MAX_UNIFORM_BUFFER_BINDINGS":24,"MAX_UNIFORM_BLOCK_SIZE":65536,"MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS":212992,"MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS":200704,"MAX_VERTEX_OUTPUT_COMPONENTS":120,"MAX_FRAGMENT_INPUT_COMPONENTS":120,"MAX_ELEMENT_INDEX":4294967294}',
}
